server:
  port: 8761

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'

eureka:
  datacenter: ${zone}
  instance:
    instance-id: ${spring.application.name}-${instanceId}-${zone}
    hostname: ${hostname}
    metadataMap:
      zone: ${zone}
  client:
    fetch-registry: true
    register-with-eureka: true
    region: region-1
    service-url:
      zone0: http://registry-0:8761/eureka/
      zone1: http://registry-1:8761/eureka/
    availability-zones:
      region-1: zone0,zone1
