version: '3'

services:

    registry-0:
       image: mradul/spring-cloud-example-registry:latest
       container_name: registry-0
       restart: always
       environment:
         instanceId: 0
         zone: zone0
         application.name: registry
         hostname: registry-0
       ports:
         - 8761:8761
       networks:
         cloud-network:
           ipv4_address: 10.7.0.2

    registry-1:
       image: mradul/spring-cloud-example-registry:latest
       container_name: registry-1
       restart: always
       environment:
         instanceId: 1
         zone: zone1
         application.name: registry
         hostname: registry-1
       ports:
         - 8762:8761
       networks:
         cloud-network:
           ipv4_address: 10.7.0.3

    user-service-0:
        image: mradul/spring-cloud-example-user-service:latest
        container_name: user-service-0
        restart: always
        environment:
          instanceId: 0
          zone: zone0
          user.name: admin
          user.password: password
          application.name: user-service
        ports:
          - 8082:8081
        networks:
          cloud-network:
            ipv4_address: 10.7.0.4

    user-service-1:
       image: mradul/spring-cloud-example-user-service:latest
       container_name: user-service-1
       restart: always
       environment:
         instanceId: 1
         zone: zone1
         user.name: admin
         user.password: password
         application.name: user-service
       ports:
         - 8083:8081
       networks:
         cloud-network:
           ipv4_address: 10.7.0.5

    zuul-0:
      image: mradul/spring-cloud-exmple-zuul:latest
      container_name: zuul-0
      restart: always
      environment:
        instanceId: 0
        zone: zone0
        user.name: admin
        user.password: password
        application.name: zuul
      ports:
        - 8084:80
      networks:
        cloud-network:
          ipv4_address: 10.7.0.6

    zuul-1:
      image: mradul/spring-cloud-exmple-zuul:latest
      container_name: zuul-1
      restart: always
      environment:
        instanceId: 1
        zone: zone1
        user.name: admin
        user.password: password
        application.name: zuul
      ports:
        - 8085:80
      networks:
        cloud-network:
          ipv4_address: 10.7.0.7

networks:
  cloud-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.7.0.0/16
