server:
  port: 80

management:
  endpoints:
    web:
      base-path: /admin

eureka:
  instance:
    instance-id: ${spring.application.name}-${instanceId}-${zone}
    prefer-ip-address: true
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
    metadataMap:
      zone: ${zone}
      some.data: some-demo-data
      management.context-path: ${management.endpoints.web.base-path}
  client:
    fetch-registry: true
    register-with-eureka: true
    region: region-1
    service-url:
      zone0: http://registry-0:8761/eureka/
      zone1: http://registry-1:8761/eureka/
    availability-zones:
      region-1: zone0,zone1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 132000

#http://cloud.spring.io/spring-cloud-netflix/1.4.x/single/spring-cloud-netflix.html#_zuul_timeouts
ribbon:
  ReadTimeout: 3000 # client makes a connection but then doesn't receive any data (at all).
  ConnectTimeout: 30000 # completing the TCP connection handshake
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true

zuul:
  retryable: true
  ignoredServices: '*'
  add-proxy-headers: true
  routes:
    user-service:
      path: /user/**
  ribbon:
    eager-load:
      enabled: true

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  aop:
    proxy-target-class: true
