server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /admin

spring:
  cloud:
    config:
      enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}-${instanceId}-${zone}
    prefer-ip-address: true
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
    metadataMap:
      zone: ${zone}
      some-data: some-data
      management.context-path: ${management.endpoints.web.base-path}
  client:
    fetch-registry: true
    register-with-eureka: true
    region: region-1
    service-url:
      zone0: http://registry-0:8761/eureka/
      zone1: http://registry-1:8761/eureka/
    availability-zones:
      region-1: zone0,zone1

debug: true