server:
  port: 8081

management:
  context-path: /admin
  security:
    enabled: true

security:
  basic:
    enabled: false
  user:
    name: ${user.name}
    password: ${user.password}

eureka:
  instance:
    instance-id: ${spring.application.name}-${instanceId}-${zone}
    prefer-ip-address: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    metadataMap:
      zone: ${zone}
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}
  client:
    fetch-registry: true
    register-with-eureka: true
    region: region-1
    service-url:
      zone0: http://registry-0:8761/eureka/
      zone1: http://registry-1:8761/eureka/
    availability-zones:
      region-1: zone0,zone1